name: Release APK
run-name: ${{ github.actor }} is Building APK 🚀
on: [push]
env:
  APK_NAME: dmw-$(date +%s).apk
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Grant primission
        run: chmod +x ./android/gradlew
      - name: Build app
        run: yarn releaseAPK
      - name: Deploy to GitHub
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.APK_NAME }}
          path: android/app/build/outputs/apk/release/app-release.apk
