name: Release APK
run-name: ${{ github.actor }} is Building APK 🚀
on: [push]
jobs:
  Release APK:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"
      - run: echo "release file will be:dmw-${{ steps.current-time.outputs.time }}.apk"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Grant primission
        run: chmod +x ./android/gradlew
      - name: Build app
        run: yarn releaseAPK
      - name: Deploy to GitHub
        env:
        TIME: "${{ steps.current-time.outputs.time }}"
        uses: actions/upload-artifact@v1
        with:
          name: dmw-${{ env.TIME }}.apk
          path: android/app/build/outputs/apk/release/app-release.apk
